### ISSUE TITLE
Server responded with a status of 403() error.

### ISSUE THREAD

**Issue by UedaTakeyuki** [hugomods/google-adsense#8]
Failed to load resources as follows:

![スクリーンショット 2023-11-06 15 26 04](https://github.com/hugomods/google-adsense/assets/893260/58cc5e4a-1afc-438e-b851-39f83a71dccf)

Any suggestions are welcome! Thank you.

**Comment by razonyang** [comment]
Hi, this module just appends the Google AdSense Script to your page, You could find more info on Google with `google adsense 403` keywords.

Some tips:

1. Is your AdSense account approval?
2. Check if your AdSense ID is correct.
3. Is there any Ad blocker active?

**Comment by UedaTakeyuki** [comment]
Thank you rasonyang! The root cause was Ad blocker.

**Comment by razonyang** [comment]
My pleasure.
